services:
  jenkins-ui:
    image: jenkins/jenkins:lts
    container_name: jenkins-ui
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-ui:/var/jenkins_home
      - jenkins-ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/sonatype-work
    ports:
      - "8081:8081"
      - "8082:8082"
volumes:
  jenkins-ui:
    driver: local 
    driver_opts:
      type: none
      device: ./volumes/jenkins
      o: bind
  jenkins-ssh:
    driver: local 
    driver_opts:
      type: none
      device: ./keys
      o: bind
  nexus-data:
    driver: local 
    driver_opts:
      type: none
      device: ./volumes/nexus
      o: bind